name: java-build
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - release
jobs:
  java-gradle-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 8
        cache: gradle
    - name: Run Gradle
      run: ./gradlew build
