name: java-build
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      - release
jobs:
  java-maven-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 8
        cache: maven
    - name: Run Maven Build
      run: ./mvnw clean package
