name: publish-snapshot-alternative
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  java-maven-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8
          cache: maven
      - name: Run Maven Build
        run: ./mvnw clean package
  publish-snapshot-jar:
    runs-on: ubuntu-latest
    needs: java-maven-build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8
          cache: maven
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.CLIENT_GPG_KEY }}
          passphrase: ${{ secrets.CLIENT_GPG_PASSPHRASE }}
      - name: Publish Snapshot
        env:
          CENTRAL_TOKEN_USERNAME: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
          CENTRAL_TOKEN_PASSWORD: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
          CLIENT_GPG_PASSPHRASE: ${{ secrets.CLIENT_GPG_PASSPHRASE }}
        run: ./mvnw clean deploy -Dgpg.passphrase="${CLIENT_GPG_PASSPHRASE}"
